# variable names like 'x', 'y' are perfectly valid for x, y coordinates
Naming/UncommunicativeMethodParamName:
  Enabled: false

# it's hardly readable otherwise
Layout/SpaceAfterNot:
  Enabled: false


# this seems to cause more trouble than what it solves: require, attr_*, DSL
# stuff all works without parenthesis.
# Style/MethodCallWithArgsParentheses:
#   Enabled: true


Style/DocumentationMethod:
  Enabled: true

Style/CharacterLiteral:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6

require:
  rubocop-rspec

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
